//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eplan_EDZ_Manager.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eplan_EDZ_Manager.Language.EN", typeof(EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export (.edz).
        /// </summary>
        public static string Btn_EdzExport {
            get {
                return ResourceManager.GetString("Btn_EdzExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string Btn_Listele {
            get {
                return ResourceManager.GetString("Btn_Listele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import (.edz).
        /// </summary>
        public static string Btn_SourceFile {
            get {
                return ResourceManager.GetString("Btn_SourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File found..
        /// </summary>
        public static string DosyaBulundu {
            get {
                return ResourceManager.GetString("DosyaBulundu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string gBox_export {
            get {
                return ResourceManager.GetString("gBox_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string gBox_import {
            get {
                return ResourceManager.GetString("gBox_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string Klasör {
            get {
                return ResourceManager.GetString("Klasör", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring File.
        /// </summary>
        public static string Lbl_DownloadInfo {
            get {
                return ResourceManager.GetString("Lbl_DownloadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 Files found..
        /// </summary>
        public static string Lbl_Find {
            get {
                return ResourceManager.GetString("Lbl_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand:.
        /// </summary>
        public static string Lbl_Marka {
            get {
                return ResourceManager.GetString("Lbl_Marka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed Size:.
        /// </summary>
        public static string Lbl_SBoyut {
            get {
                return ResourceManager.GetString("Lbl_SBoyut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Size:.
        /// </summary>
        public static string Lbl_ToplamBoyut {
            get {
                return ResourceManager.GetString("Lbl_ToplamBoyut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code:.
        /// </summary>
        public static string Lbl_Type {
            get {
                return ResourceManager.GetString("Lbl_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File transfer completed..
        /// </summary>
        public static string msg1_DosyaAktarim {
            get {
                return ResourceManager.GetString("msg1_DosyaAktarim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        public static string msg1_DosyaAktarim_Baslik {
            get {
                return ResourceManager.GetString("msg1_DosyaAktarim_Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file could not be found..
        /// </summary>
        public static string msg2_DosyaAktarim {
            get {
                return ResourceManager.GetString("msg2_DosyaAktarim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string msg2_DosyaAktarim_Baslik {
            get {
                return ResourceManager.GetString("msg2_DosyaAktarim_Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter brand information..
        /// </summary>
        public static string msgMarka {
            get {
                return ResourceManager.GetString("msgMarka", resourceCulture);
            }
        }
    }
}
