//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eplan_EDZ_Manager.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eplan_EDZ_Manager.Language.RU", typeof(RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт (.edz).
        /// </summary>
        internal static string Btn_EdzExport {
            get {
                return ResourceManager.GetString("Btn_EdzExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список.
        /// </summary>
        internal static string Btn_Listele {
            get {
                return ResourceManager.GetString("Btn_Listele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Импорт (.edz).
        /// </summary>
        internal static string Btn_SourceFile {
            get {
                return ResourceManager.GetString("Btn_SourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл найден.
        /// </summary>
        internal static string DosyaBulundu {
            get {
                return ResourceManager.GetString("DosyaBulundu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт.
        /// </summary>
        internal static string gBox_export {
            get {
                return ResourceManager.GetString("gBox_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Импорт.
        /// </summary>
        internal static string gBox_import {
            get {
                return ResourceManager.GetString("gBox_import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка.
        /// </summary>
        internal static string Klasor {
            get {
                return ResourceManager.GetString("Klasor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл загружается.
        /// </summary>
        internal static string Lbl_DownloadInfo {
            get {
                return ResourceManager.GetString("Lbl_DownloadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы не найдены..
        /// </summary>
        internal static string Lbl_Find {
            get {
                return ResourceManager.GetString("Lbl_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Марка:.
        /// </summary>
        internal static string Lbl_Marka {
            get {
                return ResourceManager.GetString("Lbl_Marka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сжатый размер:.
        /// </summary>
        internal static string Lbl_SBoyut {
            get {
                return ResourceManager.GetString("Lbl_SBoyut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общий размер:.
        /// </summary>
        internal static string Lbl_ToplamBoyut {
            get {
                return ResourceManager.GetString("Lbl_ToplamBoyut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код:.
        /// </summary>
        internal static string Lbl_Type {
            get {
                return ResourceManager.GetString("Lbl_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Передача файла завершена..
        /// </summary>
        internal static string msg1_DosyaAktarim {
            get {
                return ResourceManager.GetString("msg1_DosyaAktarim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно.
        /// </summary>
        internal static string msg1_DosyaAktarim_Baslik {
            get {
                return ResourceManager.GetString("msg1_DosyaAktarim_Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл не найден..
        /// </summary>
        internal static string msg2_DosyaAktarim {
            get {
                return ResourceManager.GetString("msg2_DosyaAktarim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string msg2_DosyaAktarim_Baslik {
            get {
                return ResourceManager.GetString("msg2_DosyaAktarim_Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите информацию о марке..
        /// </summary>
        internal static string msgMarka {
            get {
                return ResourceManager.GetString("msgMarka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа уже работает...!.
        /// </summary>
        internal static string ProgramControl {
            get {
                return ResourceManager.GetString("ProgramControl", resourceCulture);
            }
        }
    }
}
